In [17]:
#
from pandas_datareader import data as pdr
from datetime import date
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf
from functools import reduce
yf.pdr_override()

In [18]:
##############################################################################
############### FUNCTIONS FOR QUICK DATA IMPORTING AND CLEANING ##############                            
##############################################################################


#A function to import data from yahoo finance-
def y_importer(y):
    start_date = '2018-05-24'
    end_date = '2021-05-24'
    x = pdr.get_data_yahoo(y, start=start_date, end=end_date)
    return x

# a function with a for loop to fill missing values with forward fill 
#ie. the previous value
def fill_missing_val(x):
        for col in x:
            x[col].fillna(method='ffill',inplace = True)
        return   x.isnull().any()


#creating a new function to clean data
def crypto_cleaner(x):
    x['Change %']= x['Close'].pct_change()
    x['Change %'].fillna(method = 'bfill',inplace = True)
    x.reset_index(inplace=True,drop=False)
    x.Date = x.Date.astype('datetime64')
    return x.info()
    
#creating a new function to plot data
def crypto_plotter(x):
    fig, (ax1,ax2,ax3) = plt.subplots(3,1)

    ax1.plot(x['Date'],x['Close'])
    ax2.plot(x['Date'],x['Change %'],color = 'g')
    ax3.plot(x['Date'],x['Volume'],color = 'r')


    fig.subplots_adjust(left=0.1,
                    bottom=0.1, 
                    right=0.9, 
                    top=0.9, 
                    wspace=0.4, 
                    hspace=0.4)

    plt.tight_layout()
    %config InlineBackend.figure_format = 'svg'
    plt.show()

#creating a function to drop unnecessary data
def crypto_dropper(x):
    x['date']=x['Date']
    x['close']=x['Close']
    x['pct_chng']=x['Change %']
    x['vol']=x['Volume']

    x.drop(x.iloc[:,0:8], axis = 1, inplace=True)

    return x

#creating a function to combine previous 3 functions
def crypto_processor(x):
    fill_missing_val(x)
    crypto_cleaner(x)
    #crypto_plotter(x)
    crypto_dropper(x)
    return x

In [19]:
#Importing and cleaning all required crypto currencies 
#WITH JUST 10 LINES OF CODE 

btc = y_importer('BTC-USD')
crypto_processor(btc)

eth = y_importer('ETH-USD')
crypto_processor(eth)

ada = y_importer('ADA-USD')
crypto_processor(ada)

doge = y_importer('DOGE-USD')
crypto_processor(doge)

xrp = y_importer('XRP-USD')
crypto_processor(xrp)

[*********************100%***********************]  1 of 1 completed
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1093 entries, 0 to 1092
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1093 non-null   datetime64[ns]
 1   Open       1093 non-null   float64
 2   High       1093 non-null   float64
 3   Low        1093 non-null   float64
 4   Close      1093 non-null   float64
 5   Adj Close  1093 non-null   float64
 6   Volume     1093 non-null   int64
 7   Change %   1093 non-null   float64
dtypes: datetime64[ns](1), float64(6), int64(1)
memory usage: 68.4 KB
[*********************100%***********************]  1 of 1 completed
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1093 entries, 0 to 1092
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1093 non-null   datetime64[ns]
 1   Open       1093 non-null   float64
 2   High       1093 non-null   float64
 3   Low        1093 non-null   float64
 4   Close      1093 non-null   float64
 5   Adj Close  1093 non-null   float64
 6   Volume     1093 non-null   int64
 7   Change %   1093 non-null   float64
dtypes: datetime64[ns](1), float64(6), int64(1)
memory usage: 68.4 KB
[*********************100%***********************]  1 of 1 completed
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1093 entries, 0 to 1092
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1093 non-null   datetime64[ns]
 1   Open       1093 non-null   float64
 2   High       1093 non-null   float64
 3   Low        1093 non-null   float64
 4   Close      1093 non-null   float64
 5   Adj Close  1093 non-null   float64
 6   Volume     1093 non-null   int64
 7   Change %   1093 non-null   float64
dtypes: datetime64[ns](1), float64(6), int64(1)
memory usage: 68.4 KB
[*********************100%***********************]  1 of 1 completed
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1093 entries, 0 to 1092
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1093 non-null   datetime64[ns]
 1   Open       1093 non-null   float64
 2   High       1093 non-null   float64
 3   Low        1093 non-null   float64
 4   Close      1093 non-null   float64
 5   Adj Close  1093 non-null   float64
 6   Volume     1093 non-null   int64
 7   Change %   1093 non-null   float64
dtypes: datetime64[ns](1), float64(6), int64(1)
memory usage: 68.4 KB
[*********************100%***********************]  1 of 1 completed
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1093 entries, 0 to 1092
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1093 non-null   datetime64[ns]
 1   Open       1093 non-null   float64
 2   High       1093 non-null   float64
 3   Low        1093 non-null   float64
 4   Close      1093 non-null   float64
 5   Adj Close  1093 non-null   float64
 6   Volume     1093 non-null   int64
 7   Change %   1093 non-null   float64
dtypes: datetime64[ns](1), float64(6), int64(1)
memory usage: 68.4 KB

           date     close  pct_chng          vol
0    2018-05-23  0.599594  0.054042    482480992
1    2018-05-24  0.631997  0.054042    440532992
2    2018-05-25  0.611001 -0.033222    289816000
3    2018-05-26  0.612708  0.002794    213242000
4    2018-05-27  0.607881 -0.007878    186963008
...         ...       ...       ...          ...
1088 2021-05-19  1.070313 -0.327158  20523476458
1089 2021-05-20  1.185537  0.107654  13626658452
1090 2021-05-21  1.006976 -0.150616  10998911191
1091 2021-05-22  0.906317 -0.099962   8750076614
1092 2021-05-23  0.797015 -0.120600  10816054413

[1093 rows x 4 columns]

In [20]:
#renaming the columns to make combining easier
btc.columns= ['date','btc_price','btc_pct_chng','btc_vol']
eth.columns = ['date','eth_price','eth_pct_chng','eth_vol']
ada.columns = ['date','ada_price','ada_pct_chng','ada_vol']
xrp.columns = ['date','xrp_price','xrp_pct_chng','xrp_vol']
doge.columns = ['date','doge_price','doge_pct_chng','doge_vol']

In [22]:
#creating a combined df for further analysis
crypto_list = [btc,eth,ada,xrp,doge]

closing_prices= reduce(lambda  left,right: pd.merge(left,right,on=['date'],
                                            how='outer'), crypto_list)

In [23]:
closing_prices

,date,btc_price,btc_pct_chng,btc_vol,eth_price,eth_pct_chng,eth_vol,ada_price,ada_pct_chng,ada_vol,xrp_price,xrp_pct_chng,xrp_vol,doge_price,doge_pct_chng,doge_vol
0,2018-05-23,7557.819824,0.003906,6491120128,583.585022,0.031135,2995429888,0.202873,0.030147,124268000,0.599594,0.054042,482480992,0.003591,-0.025620,14899100
1,2018-05-24,7587.339844,0.003906,6049220096,601.755005,0.031135,2791099904,0.208989,0.030147,127678000,0.631997,0.054042,440532992,0.003499,-0.025620,10460200
2,2018-05-25,7480.140137,-0.014129,4867829760,586.734009,-0.024962,2110919936,0.200655,-0.039878,83368000,0.611001,-0.033222,289816000,0.003514,0.004287,10613600
3,2018-05-26,7355.879883,-0.016612,4051539968,587.280029,0.000931,1694300032,0.196567,-0.020373,60616400,0.612708,0.002794,213242000,0.003463,-0.014513,6353660
4,2018-05-27,7368.220215,0.001678,4056519936,572.668030,-0.024881,1788790016,0.193557,-0.015313,58991000,0.607881,-0.007878,186963008,0.003424,-0.011262,3494870
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1088,2021-05-19,37002.441406,-0.137661,126358098747,2460.679199,-0.272003,84482912776,1.482521,-0.260094,16313794033,1.070313,-0.327158,20523476458,0.333123,-0.300331,15072620946
1089,2021-05-20,40782.738281,0.102163,88281943359,2784.294189,0.131514,67610826680,1.810469,0.221210,11788522531,1.185537,0.107654,13626658452,0.400194,0.201340,12415484460
1090,2021-05-21,37304.691406,-0.085282,82051616861,2430.621338,-0.127024,53774070802,1.552277,-0.142611,9055414507,1.006976,-0.150616,10998911191,0.359382,-0.101981,7452862203
1091,2021-05-22,37536.632812,0.006217,57377273240,2295.705566,-0.055507,42089937660,1.463622,-0.057113,6572397780,0.906317,-0.099962,8750076614,0.342371,-0.047334,5243222352
1092,2021-05-23,34770.582031,-0.073689,78469274361,2109.579834,-0.081076,56005721977,1.325436,-0.094414,9297651823,0.797015,-0.120600,10816054413,0.308071,-0.100184,7143545371

In [25]:
closing_prices.isnull().any()

date             False
btc_price        False
btc_pct_chng     False
btc_vol          False
eth_price        False
eth_pct_chng     False
eth_vol          False
ada_price        False
ada_pct_chng     False
ada_vol          False
xrp_price        False
xrp_pct_chng     False
xrp_vol          False
doge_price       False
doge_pct_chng    False
doge_vol         False
dtype: bool